POST https://localhost:5001/posts HTTP/1.1
X-Account-Id: 3016FF6A-E082-4599-B00E-04DBFC24568E
Content-Type: image/bmp
Content-Disposition: attachment; filename="splash.bmp"
Accept: */*

< ./splash.bmp