POST https://localhost:5001/posts HTTP/1.1
X-Account-Id: 3016ff6a-e082-4599-b00e-04dbfc24568e
Content-Type: image/bmp
Content-Disposition: attachment; filename="splash.bmp"
Accept: */*

< ./splash.bmp